name: get_token_step_by_step
permissions:
  contents: write
  pull-requests: read
on:
  push:
    branches:
      - main

jobs:
  get_token_step_by_step:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Set up Python 3
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    # Step 2: Install Git
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ github.repository }}
        path: cac-content
    - name: Get the commit message and PR number
      run: |
        cd cac-content
        # Get the latest commit message (e.g., "Merge pull request #123 from branch-name")
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "Latest commit message: $COMMIT_MSG"

        # Extract the PR number from the commit message (if it's a merge commit)
        PR_NUMBER=$(echo "$COMMIT_MSG" | grep -oP '#\K\d+')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

        if [ -n "$PR_NUMBER" ]; then
          echo "Found PR number: $PR_NUMBER"
          echo "SKIP=false" >> $GITHUB_ENV
          
          # Optionally, get more details about the PR using GitHub API
          PR_INFO=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}")
          
          # Extract PR title from the response
          PR_TITLE=$(echo "$PR_INFO" | jq -r .title)
          echo "PR Title: $PR_TITLE"
          if [[ "$PR_TITLE" == *"Auto-generated PR from OSCAL content"* ]]; then
            echo "The PR comes from OSCAL content. The task of Sync CaC content to OSCAL will exit."
            echo "Skipping further checks."
            echo "SKIP=true" >> $GITHUB_ENV
          fi
        fi
    - name: Get GitHub app token
      if: ${{ env.SKIP == 'false' }}
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Get GitHub app token
      if: ${{ env.SKIP == 'false' }}
      run: |
        echo ${{ env.PR_NUMBER }}
    # Step 5: Detect the updates of CAC content
    - name: Detect files changed by PR
      if: ${{ env.SKIP == 'false' }}
      id: changed-files
      run: |
        repo=${{ github.repository }}
        # Fetch all pages of the files for the pull request
        url="repos/$repo/pulls/${{ env.PR_NUMBER }}/files"
        response=$(gh api "$url" --paginate)
        echo "$response" | jq -r '.[].filename' > filenames.txt
        echo "CHANGE_FOUND=false" >> $GITHUB_ENV
        if grep -E "controls/|.profile|rule.yml|.var" filenames.txt ; then
          echo "CHANGE_FOUND=true" >> $GITHUB_ENV
        fi
        cat filenames.txt
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    # Step 6: Setup the trestle bot environment
    - name: Checkout OSCAL content repo
      if: ${{ env.CHANGE_FOUND == 'ture' }}
      run: |
        echo "sucessful....."
    # Step 7: Check the details of the updated rule and var files
    - name: Check the deetails of the rule and var files changed by PR
      if: ${{ env.SKIP == 'false' }}
      run: |
        repo=${{ github.repository }}
        # Fetch all pages of the files for the pull request
        url="repos/$repo/pulls/${{ env.PR_NUMBER }}/files"
        response=$(gh api "$url" --paginate)
        echo "$response" | jq -r '.[].filename' > filenames.txt
        echo "CHANGE_FOUND=false" >> $GITHUB_ENV
        #PR_BRANCH=$(gh pr list --state open --json headRefName --jq '.[] | select(.headRefName | contains("check")) | .headRefName' | head -n 1)
        while IFS= read -r line; do
          if echo "$file" | grep -qE "controls/|\.profile"; then
            echo "$file" >> updated_filenames.txt
            echo "CHANGE_FOUND=true" >> $GITHUB_ENV
            echo "The change_found for finding controls and profiles: ${{ env.CHANGE_FOUND}}"
          elif [[ "$file" == *"rule.yml" ]]; then
            # Fetch the diff for the rule.yml file (or you can use a similar method you used to get diffs previously)
            if check_rule_var_updates.sh "$file" "${{ github.base_ref }}" "${{ github.head_ref }}" "description"; then
              echo "$file" >> updated_filenames.txt
              echo "CHANGE_FOUND=true" >> $GITHUB_ENV
            fi
          elif [[ "$file" == *".var" ]] && [[ check_rule_var_updates.sh "$file" "${{ github.base_ref }}" "${{ github.head_ref }}" "description" ]]; then
            echo "$file" >> updated_filenames.txt
            echo "CHANGE_FOUND=true" >> $GITHUB_ENV
            # Check if the file name ends with ".var" and contains "description" or "options" changes
        done < filenames.txt
        echo "${{ env.CHANGE_FOUND }}"
        cat filenames.txt
        if [[ -f updated_filenames.txt ]]; then
          # If the file exists, print its contents
          cat updated_filenames.txt
        else
          # If the file doesn't exist, print a message or handle accordingly
          echo "updated_filenames.txt does not exist."
        fi
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}