name: get_token_step_by_step
permissions:
  contents: write
  pull-requests: read
on:
  push:
    branches:
      - main

jobs:
  get_token_step_by_step:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Set up Python 3
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y git
    - name: Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ github.repository }}
        path: cac-content
    - name: Get the commit message and PR number
      run: |
        cd cac-content
        # Get the latest commit message (e.g., "Merge pull request #123 from branch-name")
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "Latest commit message: $COMMIT_MSG"

        # Extract the PR number from the commit message (if it's a merge commit)
        PR_NUMBER=$(echo "$COMMIT_MSG" | grep -oP '#\K\d+')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

        if [ -n "$PR_NUMBER" ]; then
          echo "Found PR number: $PR_NUMBER"
          echo "SKIP=false" >> $GITHUB_ENV
          
          # Optionally, get more details about the PR using GitHub API
          PR_INFO=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}")
          
          # Extract PR title from the response
          PR_TITLE=$(echo "$PR_INFO" | jq -r .title)
          echo "PR Title: $PR_TITLE"
          if [[ "$PR_TITLE" == *"Auto-generated PR from OSCAL content"* ]]; then
            echo "The PR comes from OSCAL content. The task of Sync CaC content to OSCAL will exit."
            echo "Skipping further checks."
            echo "SKIP=true" >> $GITHUB_ENV
          fi
        fi
    - name: Get GitHub app token
      if: ${{ env.SKIP == 'false' }}
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Get GitHub app token
      if: ${{ env.SKIP == 'false' }}
      run: |
        echo ${{ env.PR_NUMBER }}
    # Step 5: Detect the updates of CAC content
    - name: Detect files changed by PR
      if: ${{ env.SKIP == 'false' }}
      id: changed-files
      run: |
        OWNER="auto-manage-org"
        REPO="openssf"
        # Fetch all pages of the files for the pull request
        url="repos/$OWNER/$REPO/pulls/${{ env.PR_NUMBER }}/files"
        response=$(gh api "$url" --paginate)
        echo "$response" | jq -r '.[].filename' > filenames.txt
        cat filenames.txt
        echo "CHANGE_FOUND=false" >> $GITHUB_ENV
        cd cac-content
        has_change() {
          local file="$1"
          local key="$2"
          ! python compare_rule_var.py \
            --owner "$OWNER" \
            --repo "$REPO" \
            "${{ env.PR_NUMBER }}" \
            "$file" \
            "$key"
        }
        while IFS= read -r line; do
          case "$line" in
            *controls/*|*.profile*)
              echo "$line" >> updated_filenames.txt
              ;;
            *rule.yml)
              if has_change "$line" "description"; then
                echo "Change detected: The description in '$line' was updated."
                echo "$line" >> updated_filenames.txt
              fi
              ;;
            *.var)
              if has_change "$line" "description" || has_change "$line" "options"; then
                echo "Change detected: The description or options in '$line' were updated."
                echo "$line" >> updated_filenames.txt
              fi
              ;;
          esac
        done < ../filenames.txt
        if [[ -f updated_filenames.txt ]]; then
          # If the file exists, print the files
          echo "updated_filenames:"
          cat updated_filenames.txt
          echo "CHANGE_FOUND=true" >> $GITHUB_ENV
        fi
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    # Step 6: Setup the trestle bot environment
    - name: Checkout OSCAL content repo
      if: ${{ env.CHANGE_FOUND == 'true' }}
      run: |
        echo "sucessful....."
    